### ISSUE TITLE
Archiving a note changes the modified date on some other note

### ISSUE THREAD

**Issue by ghewgill** [standardnotes/desktop#146]
I've got my notes sorted by modification date. When I archive a note, that note is correctly archived but some *other* note (not sure how it's picked) is marked as modified today and pops up to the top of my list.

**Comment by mobitar** [comment]
Do you have many notes with the same modification date and time? If
so, the app has a hard time choosing so you will see this sometimes
when a re-render happens, in this case, when you pin a note.

**Comment by ghewgill** [comment]
No, they're all different because I've done all note modifications manually so far. The notes that became modified today were really some other note that hadn't been modified in a while.

**Comment by mobitar** [comment]
I think I may know what it is. And it should be fixed in beta 6. 

The issue was that when you delete/archive a note, the selection logic for which note to display next was sort of undefined. So it would load up a random note, and due to some other logic, would modify some metadata of that note.

Give beta 6 a try and see if it still happens.

**Comment by ghewgill** [comment]
That sounds like a logical explanation, but the problem appears to still happen in bets 6 I'm afraid.

**Comment by mobitar** [comment]
You're right, it happens, but this time it's not random, I believe? Meaning, it selects the next note, and not a random one, correct? That's at least one step in the direction I want. I'll investigate why it then marks the next note as modified.

**Comment by ghewgill** [comment]
Ah, yes you're right, it seems to predictably modify the metadata on the next displayed note.
