### ISSUE TITLE
Broken release tag v3.0.17

### ISSUE THREAD

**Issue by danielhass** [standardnotes/desktop#406]
Dear @mobitar,

I was about to update my [AUR package](https://aur.archlinux.org/packages/standardnotes-desktop/) to the latest release v3.0.17. After rebuilding the package I noticed that the desktop app still reports version v3.0.16. I digged a little into it and noticed that the current release tag v3.0.17 still points to a package.json which contains the old version number, see here:

https://github.com/standardnotes/desktop/blob/v3.0.17/package.json

This problem does however not exist in the latest AppImage you released.
Could you please fix the version tag for v3.0.17?

Please let me know if there is just an error on my side or if the tag is indeed pointing to the wrong commit.

Cheers,
FillFeile

**Comment by mobitar** [comment]
Fixed, thanks for the heads up.

**Comment by Zwennsch** [comment]
I am still unable to update since 3.0.17-1. Do you recommend to delete package and freshly install afterwards? Thanks in advance

**Comment by danielhass** [comment]
Hi @Zwennsch, are you installing via the mentioned AUR package?
Could you elaborate a little on your problem? What do you mean by "unable to update"?

**Comment by Zwennsch** [comment]
Hey @danielhass .Yes I am using the AUR package and am trying to install via yay/pacman. 
It seems that the system isn*t connecting to the github repo correctly. While it does work on one of my machines running on a "pure arch" it isn*t working on the other one which is running on endeavor os. 
The error I am getting in the command line reads like this:
==> Erstelle Paket: standardnotes-desktop 3.0.21-1 (Di 19 Nov 2019 17:21:44 CET)
==> Empfange Quellen...
  -> Aktualisiere das desktop git Repo...
Fordere an von origin
fatal: Konnte nicht nach github.com verbinden:
github.com[0: 140.82.118.4]: errno=Die Wartezeit für die Verbindung ist abgelaufen

error: Konnte nicht von origin anfordern
==> WARNUNG: Fehler während der Aktualisierung des desktop git Repos
  -> Aktualisiere das extensions-manager git Repo...

The system tries to connect several times, so I am getting this message a few times. At the end it shows:
==> WARNUNG: Fehler während der Aktualisierung des batch-manager git Repos
  -> standardnotes-desktop.desktop gefunden
  -> standardnotes-desktop.js gefunden
==> Überprüfe source Dateien mit sha256sums...
    desktop ... Übersprungen
    extensions-manager ... Übersprungen
    batch-manager ... Übersprungen
    standardnotes-desktop.desktop ... Durchgelaufen
    standardnotes-desktop.js ... Durchgelaufen
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Erstelle Arbeitskopie des desktop git Repos...
Klone nach 'desktop' ...
Fertig.
  -> Erstelle Arbeitskopie des extensions-manager git Repos...
Klone nach 'extensions-manager' ...
Fertig.
  -> Erstelle Arbeitskopie des batch-manager git Repos...
Klone nach 'batch-manager' ...
Fertig.
==> Beginne prepare()...
error: Pfadspezifikation 'v3.0.21' stimmt mit keinen git-bekannten Dateien überein.
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...
Error making: standardnotes-desktop
 
I don't know if this is of any help. Please let me know, if I could provide you with some more detail and thanks for any help.

**Comment by danielhass** [comment]
@Zwennsch - as you already said, this looks like a networking issue on your side. You can try to clone the repo manually in order to see if its a general problem:
```
git clone https://github.com/standardnotes/desktop.git
```
This issue seems not to be related with either standardnotes desktop itself or the AUR package.

**Comment by Zwennsch** [comment]
@danielhass If I do a git clone via command line like you mentioned the repo gets cloned without any issues.. I don't have any clue why this isn't working via update with pacman
